Account Popover Feature
spatialneuroscience/Concord pull request #30
Opened 2024-08-16 00:42 UTC by stevenguyukai

# Feature
1. Matching colors with this project
2. Shows `Avatar` `Status` `Login time` `Name` `Role` `E-mail` `Description` `Weekly work time` `In process tasks` 

![sample](https://github.com/user-attachments/assets/ec92390c-1f3f-4b30-a3d8-0ab8a8679b09)

# Todo
Enable user to edit the personal information

# Testing
Styling issue on different devices and different browsers

2024-08-18 01:00 UTC, jessieh9 requested changes

2024-08-18 01:00 UTC, jessieh9 commented on src/components/AccountPopup.jsx
> +    tasks: ["Task 1: Finish the personal information page", "Task 2: Looking into backend APIs", "Task 3: Implement the user profile"],
Don't need these tasks right now. Check the description + Figma.

2024-08-18 01:00 UTC, jessieh9 commented on src/components/AccountPopup.jsx
> +                                {userData.tasks.map((task, index) => (
same thing, don't need the tasks for now :)

2024-08-18 01:00 UTC, jessieh9 commented on src/components/AccountPopup.jsx
> +    const data = Object.entries(userData.hours).map(([week, hours]) => ({
I think the Weeks all show Week 1 in the demo when I ran your code. Can you edit to enable showing Week 1-10? Thanks.

2024-08-19 01:31 UTC, stevenguyukai commented
I have commanding out `task`, and fix the chart that always display week 1 problem

2024-08-22 00:02 UTC, jessieh9 commented
> I have commanding out `task`, and fix the chart that always display "week 1". Also I don't have the link to the Figma :o

Oh hm, for Figma link is in the frontend chat of our discord but also here for easy access https://www.figma.com/team_invite/redeem/m7USct7pyXUSdm1R6BbS9B

2024-08-22 00:08 UTC, jessieh9 approved these changes
LGTM, thanks for the changes.

2024-08-22 05:35 UTC, merged