Members display
spatialneuroscience/Concord pull request #36
Opened 2024-08-23 14:18 UTC by junxioh

The Member display page has been created, and the basic functionally works.

2024-08-23 21:06 UTC, jessieh9 requested changes

2024-08-23 21:06 UTC, jessieh9 commented on src/pages/Table.jsx
> +import React, { useEffect, useState } from "react";
What is this table for? Did you add this?

2024-08-29 07:37 UTC, junxioh commented on src/pages/Table.jsx
> +import React, { useEffect, useState } from "react";
nope，i did not import this.

2024-08-29 08:21 UTC, jessieh9 approved these changes

2024-08-29 08:21 UTC, merged