Add summary page for member
spatialneuroscience/Concord pull request #40
Opened 2024-08-29 06:33 UTC by stevenguyukai

# 1. Added `My summary` button at the account popover
<img width="437" alt="image" src="https://github.com/user-attachments/assets/9aedd84f-6e12-46b2-b10d-0950b04dd698">

# 2. Member summary page
If the `role` is admin then click the button will route to the RA summary page. If not then it will route to the member's summary page.
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/6c3860b9-8410-4b9c-a847-2e6972cb17c7">

2024-08-29 07:24 UTC, jessieh9 requested changes
Looks good, but can you also change the button styling to look more similar to the Figma? More minimalistic and less width. 
<img width="413" alt="image" src="https://github.com/user-attachments/assets/b674490c-8fb6-4b7f-bec1-76752c1b12e8">

2024-08-29 07:24 UTC, jessieh9 commented on src/App.js
> +          <Route path="/members" element={<Members/>}/>
Can you rename this to something more specific? We have a page called Members that will be implemented so can you use something else?

2024-08-29 07:24 UTC, jessieh9 commented on src/pages/Members.jsx
> +import React from "react";
Same comment, can we name the page differently?

2024-08-29 07:36 UTC, stevenguyukai commented
the button is changed to smaller size
<img width="413" alt="image" src="https://github.com/user-attachments/assets/e0ef09a8-aef4-4756-a8ab-96830d16e646">

and the naming for that module is changed from `members` to `personalSummary`

2024-08-31 07:26 UTC, jessieh9 requested changes

2024-08-31 07:26 UTC, jessieh9 commented on src/components/AccountPopup.jsx
> +                            <Button onClick={() => userData.role.toLowerCase()==="admin"?navigate("/ra-summary"):navigate("/personal-summary")} width={"40%"} backgroundColor={"white"} border={"black
Can you fetch this data from the database? We have a table for admins vs members :)

2024-08-31 07:26 UTC, jessieh9 commented on src/components/AccountPopup.jsx
>      name: "Yukai Gu",
Can you also grab the name, email, description from the DB?

2024-09-04 03:23 UTC, stevenguyukai commented
# Update
## 1. Connect to Database
Now Name, Status, Bio, and UserType(True=ADMIN, False=Member) will be saved and get from db.

<img width="413" alt="image" src="https://github.com/user-attachments/assets/ee219b68-f085-4f2f-9921-6d42610bcacf">

## 2. Edit Account
The placeholder box and title style has been changed. And the information will be saved to data base after clicking `SAVE` button.

<img width="497" alt="image" src="https://github.com/user-attachments/assets/66fadd47-c488-48c5-8e27-f2ac5d3eddf9">

## 3. Success toast
After saving successfully, a toast will show to the user.

<img width="864" alt="image" src="https://github.com/user-attachments/assets/c5a5923c-d5ae-431d-83f7-ce8d6c9cb6b0">

## 4. Database modify
Add a column in Public.Users called `status` which will store users self-wrote word

<img width="322" alt="image" src="https://github.com/user-attachments/assets/ef2ff22f-d5c5-421f-8c1a-ccd1de4c818d">



# Close
This will close issue #44

2024-09-06 06:20 UTC, jessieh9 approved these changes

2024-09-06 06:21 UTC, merged