Add feature for project edit/update
spatialneuroscience/Concord pull request #42
Opened 2024-09-01 16:27 UTC by Will15800

Added the edit icon for the Project card. Implemented functionality for the Edit and Update feature for the projects. Created a form to edit and update individual projects. The changes are updated in the database too.

2024-09-04 04:45 UTC, RichardSima2021 commented on src/components/EditProject.jsx
> +          if (!error && data.length > 0 && data[0].user_type) {
Encapsulate logic into helper function for code cleanup

2024-09-04 07:19 UTC, Will15800 commented
I did some code cleanup and created helper functions, also resolved merge conflict

2024-09-05 01:43 UTC, jessieh9 commented
> I did some code cleanup and created helper functions, also resolved merge conflict

I see, in the future you can leave merge conflicts to us so it's less work for the devs :))

2024-09-05 04:06 UTC, jessieh9 requested changes

2024-09-05 04:06 UTC, jessieh9 commented on src/components/ProjectCard.jsx
> +            <Spacer />
Is this imported from Chakra?

2024-09-05 04:06 UTC, jessieh9 commented on src/components/ProjectCard.jsx
> +            <EditProject
If you use this, remove the Pencil Icon, we don't need two edit buttons.

2024-09-05 04:37 UTC, Will15800 commented on src/components/ProjectCard.jsx
> +            <EditProject
Yes I am using another Icon inside EditProject. I will remove the pencil icon

2024-09-05 04:43 UTC, Will15800 commented on src/components/ProjectCard.jsx
> +            <Spacer />
Yes it's used to create space between Edit and Project date

2024-09-05 05:15 UTC, jessieh9 commented on src/components/ProjectCard.jsx
> +            <Spacer />
Can you import it? It's not imported yet.

2024-09-05 05:20 UTC, Will15800 commented on src/components/ProjectCard.jsx
> +            <Spacer />
Got it

2024-09-12 22:14 UTC, jessieh9 approved these changes
LGTM

2024-09-12 22:14 UTC, merged