Individual projects layout
spatialneuroscience/Concord pull request #47
Opened 2024-09-05 14:11 UTC by zhanhaoruan

1. The main individual project page layout and nav bar navigation functionality. 

https://github.com/user-attachments/assets/cc26eb16-9ea7-460d-9720-b27f87106e0e

2. For the Goal, Hypothesis, and so on, clicking on each one allows to show the information.

https://github.com/user-attachments/assets/ad53ce9e-a991-4a5c-9bff-afbc234136b0

3. The pinned documents showcase and onlick navigation functionality.

https://github.com/user-attachments/assets/080788ed-9a65-4cf1-a538-6d96d23ee7eb

ps:
1. I switch the icons of Tasks and Documents to align with the icons from the study page. I also changed the icon for the calendar since this appears to be more intuitive. If you think otherwise, please let me know so I can make changes. 

2. Some suggestions on some more advanced functionality. Right now the task from the nav bar is redirecting to the task page. I am thinking about modifying the task page so that when I click it from the individual project page, the task page will only show tasks that are related to this project. Same to the document page, calendar page (which is not implemented yet), and the members page.

2024-09-06 06:29 UTC, jessieh9 commented
> 1. The main individual project page layout and nav bar navigation functionality.
> 
>  main_layout_nav.1.mov 
> 2. For the Goal, Hypothesis, and so on, clicking on each one allows to show the information.
> 
>  click_show.1.mov 
> 3. The pinned documents showcase and onlick navigation functionality.
> 
>  pinned_documents.1.mov 
> ps:
> 
> 1. I switch the icons of Tasks and Documents to align with the icons from the study page. I also changed the icon for the calendar since this appears to be more intuitive. If you think otherwise, please let me know so I can make changes.
> 2. Some suggestions on some more advanced functionality. Right now the task from the nav bar is redirecting to the task page. I am thinking about modifying the task page so that when I click it from the individual project page, the task page will only show tasks that are related to this project. Same to the document page, calendar page (which is not implemented yet), and the members page.

Very great and thorough demo! For the icons, they're great! Thanks for taking the initiative.
On the functionality of the task page and members, yes later on we will fix it such that each projects have their own tasks and members page. Thanks for looking into it :)))

2024-09-06 06:46 UTC, jessieh9 requested changes

2024-09-06 06:46 UTC, jessieh9 commented on src/pages/IndividualProject.jsx
> +                                    <CardHeader pt={2} pb={0} display='flex' justifyContent='flex-end'>
instead of pixels for width and height of card, maybe try using percentages so that it shows up the same for various screens / dimensions. Using pixels might only look well for your end :)

2024-09-06 06:46 UTC, jessieh9 commented on src/pages/IndividualProject.jsx
> +                                    <CardHeader pt={2} pb={0} display='flex' justifyContent='flex-end'>
Can also try using vh or vw

2024-09-06 06:46 UTC, jessieh9 commented on src/pages/IndividualProject.jsx
> +                                    <CardHeader pt={2} pb={0} display='flex' justifyContent='flex-end'>
Other than this small design fix, the PR looks very very good!

2024-09-08 15:00 UTC, zhanhaoruan commented on src/pages/IndividualProject.jsx
> +                                    <CardHeader pt={2} pb={0} display='flex' justifyContent='flex-end'>
I just pushed the update. I changed many px to percentages and the result looks the same at my end. Please take look and let me know if there any more changes need to make :)

2024-09-12 22:57 UTC, jessieh9 approved these changes

2024-09-12 23:03 UTC, merged